### ISSUE TITLE
no error but not success either

### ISSUE THREAD

**Issue by huahuayu** [huahuayu/go-mev-geth#1]
## problem

I use this repo to build & sign tx, send it to relay, the http code is 200(which means the header `X-Flashbots-Signature` is good), and no error msg gets from the relay(no matter `eth_callBundle` or `eth_sendBundle`).

from etherscan I know the tx is not mined also.

I have test in mainnet as well as goerli testnet, same result.

repsonse from the relay:

{[] {0xc00023a000} <nil> <nil>}

## payload

this is my payload

```json
{
    "jsonrpc":"2.0",
    "method":"eth_callBundle",
    "params":[
        [
            "0xf88582018b80828474945392b5fe24367d4d8079de9c3c6e2b7b2eb632a701a412514bba000000000000000000000000000000000000000000000000000000000000000026a0d7ef58fc03c0d5be4d3c98631dec94d72a76e7052515805e964852c8852f2724a039093501bf27df3d6acfdcccab9144c1a7bb6d0b9e488ecf37d5fb415635ef91",
            "0xf88c82018c8082a96b945392b5fe24367d4d8079de9c3c6e2b7b2eb632a7872386f26fc10001a412514bba000000000000000000000000000000000000000000000000002386f26fc1000026a0053d00e9fa9627ded5d7f85c1eb1808198d60170b5c4198ec289ea7bb909b7b8a05d9d5cf0ad7f0da4da95d1f3fb397f17a6f5197670fc0ac9ce5acbadac635ac2"
        ],
        "0xbb858b",
        0,
        0
    ],
    "id":1
}
```

**Comment by riceluxs1t** [comment]
I get this behavior too

**Comment by huahuayu** [comment]
It's been clarified that it's the testnet problem.
